osx_image: xcode10
language: swift
install:
- cd LivrDemo && bundle install
script: 
- rm -rf ~/Library/Developer/Xcode/DerivedData
- sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
- bundle exec fastlane test