osx_image: xcode9.4
language: swift

cache:
- bundler

install:
- bundle install

script: 
- bundle exec fastlane test

### To be run when releasing versions ### - Travis doesn't support different jobs by branches, yet
- bundle exec fastlante tag
- bundle exec fastlante publish

branches:
   only: 
     - master